### ISSUE TITLE
Encrypt string with dash will decrypt badly

### ISSUE THREAD

**Issue by xArthasx** [kokke/tiny-AES128-C#14]
I think it's the dashes.

	uint8_t input[17] = "2014-02-20 13:27";
	// strftime((char*)input, sizeof(input), "%Y-%m-%d %H %M", &tstruct);
	std::cout << input<<"\n";
	uint8_t output[ sizeof(input) +16];
	AES128_ECB_encrypt(input, key, output);
	size_t size = sizeof(output);
	uint8_t decrypted[17];
	AES128_ECB_decrypt(output, key, decrypted);
	std::cout << decrypted<< "\n";
Will output:
![image](https://cloud.githubusercontent.com/assets/422970/6307088/0d850094-b907-11e4-8e9e-61a6e901356f.png)

**Comment by reattiva** [comment]
Hi, *AES128_ECB_encrypt* works only on one block (16 bytes), your string has 17 bytes, so the null terminator (the 17° byte) is not encrypted nor decrypted.
If you try with the string "2014-02-20 13:2" it should work.

**Comment by kokke** [comment]
Thank you @reattiva for solving this issue :)
