### ISSUE TITLE
Could you provide more usage examples ?

### ISSUE THREAD

**Issue by AsharLohmar** [kokke/tiny-AES128-C#15]
Hi,
I couldn't find another way to contact you so I'm using this.
Could you be kind enough to share some usage examples ?
I've seen the tests so I've managed to understand  most of it, but I have problems trying to use a key longer then 16 bits.
Thank you

**Comment by d0773d** [comment]
Hi AsharLohmar.  AES128 uses a 16bit key.  tiny-AES128 library only uses AES128 cipher, hence 16bit key.

**Comment by AsharLohmar** [comment]
[damn, now I look so stupid]
Hi, 
yes, you are right (of course).
when I've wrote the question I was way too "focused" on the "AES" part and lost the "128" part and it's meaning. 
Thank you

**Comment by androidovshchik** [comment]
Hi
I wrote an android app with this library via ndk
Have a look! Enjoy
