### ISSUE TITLE
encrypt different between openssl and this

### ISSUE THREAD

**Issue by yumm007** [kokke/tiny-AES128-C#21]
I use openssl encrypt a string, the result is "8oaoH1JOBl3+QgRoEc5l0pYF5aMN1+p7AT/xAgUIST8="
>echo -n "1234567890abcdef" | openssl enc -K 2b7e151628aed2a6abf7158809cf4f3c -iv 000102030405060708090a0b0c0d0e0f -aes-128-cbc -base64 

but when use functuon AES128_CBC_encrypt_buffer, the result(after base64) is
 > "8oaoH1JOBl3+QgRoEc5l0g=="

I has set the key and IV as same sa openssl

Why are there have two differnet result? Thank you!
How can i enable pading in `AES128_CBC_encrypt_buffer`

**Comment by yumm007** [comment]
This problem has fixed, I will make a push request.

**Comment by bateller** [comment]
What was the issue?

**Comment by yumm007** [comment]
AES 128 need padding bytes as PKCS5.
The diff is https://github.com/yumm007/tiny-AES128-C/commit/f338083ed693d51da1f7ba44233957cfa48927ce

**Comment by bateller** [comment]
Thank you.

**Comment by redmanit** [comment]
How did you convert uint8_t array to base 64 String, yumm007?

**Comment by redmanit** [comment]
How did you convert uint8_t array to base 64 String, @yumm007 ?
