### ISSUE TITLE
Use memcmp instead of strncmp in test.c

### ISSUE THREAD

**Issue by rosswille** [kokke/tiny-AES128-C#27]
The function strncmp() will stop comparing when it encounters a NULL character in either string. For example, given the following data, strncmp() would report 0 (match), whereas memcmp() would report non-zero (mismatch).

uint8_t buf1[] = {3, 0, 1, 2};
uint8_t buf2[] = {3, 0, 1, 3};

false_result = strncmp((char *)buf1, (char *)buf2, 4);
true_result = memcmp(buf1, buf2, 4);

Using memcmp() for comparing byte sequences which are not null-terminated strings will fix this problem.

**Comment by kokke** [comment]
You are right! Thank you for noting this :) I will change the test-code immediately.
