### ISSUE TITLE
can the CBC mode use  randon number for the iv ?

### ISSUE THREAD

**Issue by dinomycle** [kokke/tiny-AES128-C#32]
hello
 while using this aes code in CBC mode, i want to use random number, what all are the changes required for the same

Thanks for the Support

**Comment by kokke** [comment]
I am not sure what you are asking really. Could you elaborate a bit ? :)

**Comment by waydaws** [comment]
Kokke, it looks like in your test.c you use a non-random initialization vector.  For AES CBC it has to random and unique.  That's what he's saying.   You have,   uint8_t iv[] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f }; which can't be described as random.

**Comment by kokke** [comment]
Ah, thanks for the explanation waydaws :)

Well the test checks if the code can repeat the test vectors in the NIST document referenced in the readme.

The IV is a byte array and can be filled by other means than static initialization, e.g. by using a random number generator like rand() from the std.library or something like this: http://burtleburtle.net/bob/rand/smallprng.html

I can recommend the linked "smallprng". It is tiny, fast and runs in constant time. It also passes the diehard-tests according to the owner.

**Comment by dinomycle** [comment]
hello kokke,
 yes, what waydaws  was saying only i was trying to ask. thanks for the explanation and comments
