### ISSUE TITLE
Decryption problem

### ISSUE THREAD

**Issue by vjkolaventy** [kokke/tiny-AES128-C#57]
Hi

When I use the tiny-AES128 for both encryption and decryption it is working fine. But when I try to decrypt the same with any other program I get a partial decryption. I am not very good at C. So I am not sure if I am doing something wrong or if there is a bug. Below is are the details.

Key & IV: same as in text.c
#uint8_t encrypt_key[] = { 0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c };
#uint8_t iv[]  = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f };

Encrypted Hex: AE8384D8E0AF32B801DA80E5CD05D7E8E916E853CAB551AB91966F540694A4D9

Plain Text: AAA000000001#starnet000000000000

When I decrypting the same using pyaes (python) and online (http://aes.online-domain-tools.com/) I the following decrypted message.

AAA000000001#sta???Ԛ?9???8??

The message is garbled after sta. Please let me know what is wrong.

Thanks & Regards
Vijay

**Comment by vjkolaventy** [comment]
Sorry forgot to mention that I was using AES128_CBC_decrypt_buffer

**Comment by denisdemaisbr** [comment]
@vjkolaventy u can provide a full example to avaliate ?

**Comment by vjkolaventy** [comment]
Sorry. I gave the 64 byte string instead of 16 byte. My bad.

**Comment by vjkolaventy** [comment]
I am using your aes128 in an embedded device using ADE5169 from Analogic which has just 2KB RAM. Your code fits the bill perfectly. Great Job. Thank you.

PS. This is better than the TI AES.

**Comment by vjkolaventy** [comment]
Hi

I am using your code in an iot device. I made a mistake in giving a hex string of 64 bytes. I split into 2 strings of 32 bytes and it is working fine. Thanks for your prompt response. 

Regards

Dr. Vijay Kolaventy
