### ISSUE TITLE
Different input

### ISSUE THREAD

**Issue by davidepic91** [kokke/tiny-AES128-C#59]
Premise: I'm not confident with C.
Is there a way to use this method:

void AES_CBC_encrypt_buffer(uint8_t* output, uint8_t* input, uint32_t length, const uint8_t* key, const uint8_t* iv);

by passing (char* output, char* input, uint32_t length, const char* key, const char* iv) ?

**Comment by kokke** [comment]
`uint8_t` just means an unsigned 8-bit integer type, which is usually what an `unsigned char` is.
You should be able to use `char*` and `uint8_t*` interchangeably in this case.

**Comment by davidepic91** [comment]
Ok perfect ! thank you so much !

**Comment by kokke** [comment]
No problem :) Thanks for taking an interest in this project :)
