### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by federicoVS** [kokke/tiny-AES128-C#60]
I try to compile the test.c file and I obtain the following errors:
```
"_AES_CBC_decrypt_buffer", referenced from:
      _test_decrypt_cbc in test-602b3e.o
  "_AES_CBC_encrypt_buffer", referenced from:
      _test_encrypt_cbc in test-602b3e.o
  "_AES_ECB_decrypt", referenced from:
      _test_decrypt_ecb in test-602b3e.o
  "_AES_ECB_encrypt", referenced from:
      _test_encrypt_ecb in test-602b3e.o
      _test_encrypt_ecb_verbose in test-602b3e.o
```

Does someone know how to fix this? Thanks in advance.

**Comment by kokke** [comment]
`test.c` depends on the functions defined and exported from `aes.c`.
You need to compile that file and link it against the rest of your binary.

You are getting the above errors because you are not compiling all the files needed, and your linker tells you what is missing.
